### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by iCrawl** [SunDwarf/OWAPI#120]
Dividing by zero 👍 

`https://owapi.net/api/v3/u/iCrawl-21881/blob`
`https://owapi.net/api/v3/u/iCrawl-21881/stats`

I think on all endpoints lol.

If you need some more info, I hosted it myself to get a sweet traceback

```
2016-12-21 20:12:03,329 - [INFO] OWAPI -> Cache hit for `_real_get_body('https://playoverwatch.com/en-us/career/pc/us/iCrawl-21881',)`
2016-12-21 20:12:03,329 - [INFO] OWAPI -> Cache hit for `_real_get_body('https://playoverwatch.com/en-us/career/pc/kr/iCrawl-21881',)`
2016-12-21 20:12:03,334 - [INFO] OWAPI -> Cache hit for `_real_get_body('https://playoverwatch.com/en-us/career/pc/eu/iCrawl-21881',)`
2016-12-21 20:12:03,396 - [ERROR] OWAPI -> Unhandled exception - Blizzard format probably changed!
Traceback (most recent call last):
  File "/home/crawl/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 87, in invoke_function
    result = await result
  File "/home/crawl/OWAPI/owapi/v3/v3_util.py", line 118, in _rl_inner2
    return await func(ctx, *args, **kwargs)
  File "/home/crawl/OWAPI/owapi/v3/__init__.py", line 62, in get_blob
    d["stats"]["competitive"] = parsing.bl_parse_stats(result, mode="competitive")
  File "/home/crawl/OWAPI/owapi/v3/parsing.py", line 141, in bl_parse_stats
    wr = floor((wins / (games - ties)) * 100)
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/crawl/OWAPI/venv/lib/python3.5/site-packages/kyoukai/app.py", line 251, in process_request
    result = await matched.invoke(ctx, params)
  File "/home/crawl/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 170, in invoke
    return await self.invoke_function(ctx, pre_hooks, post_hooks, **params)
  File "/home/crawl/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 95, in invoke_function
    raise InternalServerError() from e
werkzeug.exceptions.InternalServerError: 500: Internal Server Error
```

**Comment by SunDwarf** [comment]
Fixed and pushed to prod, thanks!

**Comment by iCrawl** [comment]
Are you sure? 💯 

Git pulled, tested it same error, if you pushed it to production on your live site already its also throwing the error still.

**Comment by SunDwarf** [comment]
Note to self: Test changes before pushing
