### ISSUE TITLE
Type __args__ Attribute Error

### ISSUE THREAD

**Issue by dkim616** [SunDwarf/OWAPI#139]
## Issue

Can't start OWAPI server as per instructions. Typeguard error? Running on python 3.6 venv with all required packages (OSX).

## Links that cause the issue

```
(venv) DK@D OWAPI (master) $ PYTHONPATH=. asphalt run config.yml
Traceback (most recent call last):
  File "/Users/DK/workspace/overwatch/OWAPI/venv/bin/asphalt", line 7, in <module>
    from asphalt.core.command import main
  File "/Users/DK/workspace/overwatch/OWAPI/venv/lib/python3.6/site-packages/asphalt/core/__init__.py", line 1, in <module>
    from .component import *
  File "/Users/DK/workspace/overwatch/OWAPI/venv/lib/python3.6/site-packages/asphalt/core/component.py", line 8, in <module>
    from asphalt.core.context import Context
  File "/Users/DK/workspace/overwatch/OWAPI/venv/lib/python3.6/site-packages/asphalt/core/context.py", line 111, in <module>
    class Context:
  File "/Users/DK/workspace/overwatch/OWAPI/venv/lib/python3.6/site-packages/asphalt/core/context.py", line 134, in Context
    finished = Signal(ContextFinishEvent)
  File "/Users/DK/workspace/overwatch/OWAPI/venv/lib/python3.6/site-packages/asphalt/core/event.py", line 92, in __init__
    assert check_argument_types()
  File "/Users/DK/workspace/overwatch/OWAPI/venv/lib/python3.6/site-packages/typeguard.py", line 308, in check_argument_types
    check_type(argname, value, expected_type, typevars_memo)
  File "/Users/DK/workspace/overwatch/OWAPI/venv/lib/python3.6/site-packages/typeguard.py", line 237, in check_type
    checker_func(argname, value, expected_type, typevars_memo)
  File "/Users/DK/workspace/overwatch/OWAPI/venv/lib/python3.6/site-packages/typeguard.py", line 47, in check_callable
    if isinstance(expected_type.__args__, tuple):
AttributeError: type object 'type' has no attribute '__args__'
```

**Comment by SunDwarf** [comment]
This seems like it should probably be raised upstream at agronholm/typeguard.

**Comment by dkim616** [comment]
This issue was fixed by updating my typeguard package to the latest, 2.1.1.
