### ISSUE TITLE
ModuleNotFoundError and LookupError

### ISSUE THREAD

**Issue by feedmei** [SunDwarf/OWAPI#141]
## Issue

```
(venv) [arch@archbox OWAPI]$ PYTHONPATH=. asphalt run config.yml
INFO:asphalt.core.runner:Running in development mode
Traceback (most recent call last):
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/asphalt/core/util.py", line 30, in resolve_reference
    obj = import_module(modulename)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/arch/www/owapi2/OWAPI/owapi/app.py", line 21, in <module>
    from owapi.v3 import api_v3
  File "/home/arch/www/owapi2/OWAPI/owapi/v3/__init__.py", line 12, in <module>
    from owapi.v3.v3_util import with_ratelimit
  File "/home/arch/www/owapi2/OWAPI/owapi/v3/v3_util.py", line 11, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arch/www/owapi2/venv/bin/asphalt", line 11, in <module>
    sys.exit(main())
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/asphalt/core/command.py", line 34, in run
    run_application(**config)
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/asphalt/core/runner.py", line 90, in run_application
    component = component_types.create_object(**component)
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/asphalt/core/util.py", line 146, in create_object
    plugin_class = self.resolve(type)
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/asphalt/core/util.py", line 120, in resolve
    return resolve_reference(obj)
  File "/home/arch/www/owapi2/venv/lib/python3.6/site-packages/asphalt/core/util.py", line 33, in resolve_reference
    'error resolving reference {}: could not import module'.format(ref)) from e
LookupError: error resolving reference owapi.app:APIComponent: could not import module
```

## Links that cause the issue

When I run
`PYTHONPATH=. asphalt run -l uvloop config.yml`
with a Python 3.6 venv on Arch Linux I get this:
`LookupError: error resolving reference owapi.app:APIComponent: could not import module`
and
`ModuleNotFoundError: No module named 'yaml'`

## Solution

Simply changing `asphalt>=2.0.0` to `asphalt==2.0.0` in `requirements.txt` and running `pip install -r requirements.txt` again fixed this for me. This suggests an incompatibility with newer versions of asphalt 🕵️ 

Great project by the way 👍 💯 🔥

**Comment by SunDwarf** [comment]
Fixed in the latest commit.
