### ISSUE TITLE
Cannot import name PROTOCOL_ERROR

### ISSUE THREAD

**Issue by skwerlman** [SunDwarf/OWAPI#150]
## Issue

I've started to get this set up locally, but whenever I make a request (say, `curl 127.0.0.1:4444/api/v3/u/skwerlman-1242/stats`), OWAPI errors out and never sends anything back to `curl`.

After erroring out once, the app stops responding to any further requests.

```
(venv) ┌[wheeler☮bfs]-(~/OWAPI)-[git://master ✗]-
└> PYTHONPATH=. asphalt run -l uvloop config.yml
INFO:asphalt.core.runner:Running in development mode
INFO:asphalt.core.runner:Switched event loop policy to uvloop.EventLoopPolicy
2017-03-26 04:56:27,540 - [INFO] asphalt.core.runner -> Starting application
2017-03-26 04:56:27,596 - [INFO] asphalt.redis.component -> Configured Redis client (redis / ctx.redis; address=('127.0.0.1', 6379), db=2)
2017-03-26 04:56:27,596 - [INFO] Kyoukai -> Kyoukai serving on 127.0.0.1:4444.
2017-03-26 04:56:27,597 - [INFO] OWAPI -> Started OWAPI server.
2017-03-26 04:56:27,597 - [INFO] asphalt.core.runner -> Application started
2017-03-26 04:58:26,970 - [ERROR] asyncio -> Unhandled exception in event loop
Traceback (most recent call last):
  File "uvloop/handles/streamserver.pyx", line 126, in uvloop.loop.__uv_streamserver_on_listen (uvloop/loop.c:78941)
  File "uvloop/handles/streamserver.pyx", line 49, in uvloop.loop.UVStreamServer._on_listen (uvloop/loop.c:77750)
  File "/home/wheeler/OWAPI/venv/lib/python3.5/site-packages/kyoukai/asphalt.py", line 136, in get_protocol
    mod = importlib.import_module(self.backend)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/wheeler/OWAPI/venv/lib/python3.5/site-packages/kyoukai/backends/httptools_.py", line 17, in <module>
    from kyoukai.backends.http2 import H2KyoukaiProtocol
  File "/home/wheeler/OWAPI/venv/lib/python3.5/site-packages/kyoukai/backends/http2.py", line 37, in <module>
    from h2.errors import PROTOCOL_ERROR
ImportError: cannot import name 'PROTOCOL_ERROR'
```

If run with `PYTHONPATH=. asphalt run config.yml`, `curl` is just sent an RST whenever it tries to make a request, and nothing is logged by the app.

## Links that cause the issue

All links

**Comment by skwerlman** [comment]
Actually, just realised this is fixed in Kyoukai master. My bad.
