### ISSUE TITLE
How run OWAPI with https

### ISSUE THREAD

**Issue by Neragoth** [SunDwarf/OWAPI#167]
Hello everybody, 
When using OWAPI, I can use it as http, but I cant make it work with https and haven't found other post about it. 
I run redis server and I change this line "use_redis: False" to True.
```

(venv) neragoth@vps335877:/home/www/OWAPI$ PYTHONPATH=. asphalt run config.yml
INFO:asphalt.core.runner:Running in development mode
2017-05-12 10:22:38,149 - [INFO] asphalt.core.runner -> Starting application
2017-05-12 10:22:38,179 - [INFO] Kyoukai -> Scanned 9 routes over 2 child blueprint(s), building URL mapping now.
2017-05-12 10:22:38,181 - [INFO] Kyoukai -> Built route mapping with 9 rules.
2017-05-12 10:22:38,187 - [INFO] asphalt.redis.component -> Configured Redis client (redis / ctx.redis; address=('mywebsite.com', 6379), db=1)
2017-05-12 10:22:38,203 - [INFO] Kyoukai -> Kyoukai serving on mywebsite.com:4444.
2017-05-12 10:22:38,204 - [INFO] OWAPI -> Started OWAPI server.
2017-05-12 10:22:38,204 - [INFO] asphalt.core.runner -> Application started

```

when I check my website 

   ```
2017-05-12 10:15:27,422 - [ERROR] OWAPI -> Unhandled exception - Blizzard format probably changed!
Traceback (most recent call last):
  File "/var/www/html/venv/lib/python3.5/site-packages/kyoukai/app.py", line 273, in process_request
    result = await matched.invoke(ctx, params)
  File "/var/www/html/venv/lib/python3.5/site-packages/kyoukai/route.py", line 244, in invoke
    return await self.invoke_function(ctx, pre_hooks, post_hooks, params)
  File "/var/www/html/venv/lib/python3.5/site-packages/kyoukai/route.py", line 110, in invoke_function
    result = await result
  File "/var/www/html/OWAPI/owapi/v3/v3_util.py", line 101, in _rl_inner2
    if not (await ctx.redis.exists(built)):
  File "/var/www/html/venv/lib/python3.5/site-packages/aioredis/commands/__init__.py", line 41, in execute
    conn = yield from self.get_atomic_connection()
  File "/var/www/html/venv/lib/python3.5/site-packages/aioredis/commands/__init__.py", line 50, in get_atomic_connection
    *self._conn_args, **self._conn_kwargs)
  File "/var/www/html/venv/lib/python3.5/site-packages/aioredis/connection.py", line 70, in create_connection
    host, port, ssl=ssl, loop=loop)
  File "/usr/lib/python3.5/asyncio/streams.py", line 75, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 695, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.5/asyncio/base_events.py", line 682, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 402, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 432, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('mywebsite.com', 6379)
2017-05-12 10:15:27,425 - [INFO] Kyoukai -> GET /api/v3/u/Mobi-2683/stats - 500
```

Thanks for your help

**Comment by azah** [comment]
```
ConnectionRefusedError: [Errno 111] Connect call failed ('mywebsite.com', 6379)
```

Change mywebsite.com to localhost

**Comment by devyg** [comment]
You have to configure the Kyoukai server to enable HTTPS.
Here is how I did it : 
- create your certificates (I used letsencrypt)
- create a ../letsencrypt directory with symbolic links to fullchain.pem and privkey.pem
- update the config.yml file with the following (as found here [Kyoukai HTTPS](https://mirai.veriny.tf/en/latest/adv/tls.html) : 
````json
ssl:
        enabled: true
        ssl_certfile: ../letsencrypt/fullchain.pem
        ssl_keyfile: ../letsencrypt/privkey.pem
```
Hope this helps.

**Comment by SunDwarf** [comment]
The above post is correct; ideally you would use a reverse proxy such as nginx to provide TLS instead, however. I'll add a note to the README at some point explaining this however.

**Comment by Neragoth** [comment]
Thank everyone, it works perfectly now.
