### ISSUE TITLE
"Unhandled exception - Blizzard format probably changed!" on self-hosted instance

### ISSUE THREAD

**Issue by NamoDev** [SunDwarf/OWAPI#176]
## Issue
When self-hosting the latest code from the repository (at commit e3e6c1d1d0e47ccea14c340641a35e7ba7b38c63), player data cannot be retrieved.

## Links that cause the issue
Just accessing any player profile through the self-hosted API instance. This error pops up on the console of the server:
```
2017-06-12 10:43:07,802 - [INFO] OWAPI -> Started OWAPI server.
2017-06-12 10:43:07,802 - [INFO] asphalt.core.runner -> Application started
2017-06-12 10:43:12,688 - [ERROR] Kyoukai -> Unhandled exception in route function
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kyoukai/app.py", line 273, in process_request
    result = await matched.invoke(ctx, params)
  File "/usr/local/lib/python3.5/dist-packages/kyoukai/route.py", line 244, in invoke
    return await self.invoke_function(ctx, pre_hooks, post_hooks, params)
  File "/usr/local/lib/python3.5/dist-packages/kyoukai/route.py", line 101, in invoke_function
    _ = await hook(ctx)
  File "/app/OverwatchAPI/owapi/app.py", line 93, in start_profiling
    ctx.cfg['owapi_profiling_obj'] = pr
  File "/usr/local/lib/python3.5/dist-packages/asphalt/core/context.py", line 152, in __getattr__
    raise AttributeError('no such context variable: {}'.format(name))
AttributeError: no such context variable: cfg
2017-06-12 10:43:12,688 - [ERROR] OWAPI -> Unhandled exception - Blizzard format probably changed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kyoukai/app.py", line 273, in process_request
    result = await matched.invoke(ctx, params)
  File "/usr/local/lib/python3.5/dist-packages/kyoukai/route.py", line 244, in invoke
    return await self.invoke_function(ctx, pre_hooks, post_hooks, params)
  File "/usr/local/lib/python3.5/dist-packages/kyoukai/route.py", line 101, in invoke_function
    _ = await hook(ctx)
  File "/app/OverwatchAPI/owapi/app.py", line 93, in start_profiling
    ctx.cfg['owapi_profiling_obj'] = pr
  File "/usr/local/lib/python3.5/dist-packages/asphalt/core/context.py", line 152, in __getattr__
    raise AttributeError('no such context variable: {}'.format(name))
AttributeError: no such context variable: cfg
2017-06-12 10:43:12,689 - [INFO] Kyoukai -> GET /api/v3/u/BetreyerZ-1933/blob - 500

```

Everything is configured per tutorial except that I've disabled ratelimits in the settings file.

**Comment by SunDwarf** [comment]
This issue would have been caused because `do_profiling` was set to True in the config file. I fixed the issue either way.
