### ISSUE TITLE
Getting a TypeError: route() got an unexpected keyword argument 'reverse_hooks'

### ISSUE THREAD

**Issue by Doezer** [SunDwarf/OWAPI#177]
## Issue
Hello,
OWAPI was loading indefinitely since a few days when asking about a profile, so I updated my local repo. Now, it doesn't launch at all and returns this traceback:

```
(venv) OWAPI# PYTHONPATH=. python3.6 -O ./venv/bin/asphalt run config.yml
INFO:asphalt.core.runner:Running in production mode
Traceback (most recent call last):
  File "./venv/bin/asphalt", line 11, in <module>
    sys.exit(main())
  File "/home/doezer/git_projects/OWAPI/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/doezer/git_projects/OWAPI/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/doezer/git_projects/OWAPI/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/doezer/git_projects/OWAPI/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/doezer/git_projects/OWAPI/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/doezer/git_projects/OWAPI/venv/lib/python3.6/site-packages/asphalt/core/command.py", line 34, in run
    run_application(**config)
  File "/home/doezer/git_projects/OWAPI/venv/lib/python3.6/site-packages/asphalt/core/runner.py", line 90, in run_application
    component = component_types.create_object(**component)
  File "/home/doezer/git_projects/OWAPI/venv/lib/python3.6/site-packages/asphalt/core/util.py", line 146, in create_object
    plugin_class = self.resolve(type)
  File "/home/doezer/git_projects/OWAPI/venv/lib/python3.6/site-packages/asphalt/core/util.py", line 120, in resolve
    return resolve_reference(obj)
  File "/home/doezer/git_projects/OWAPI/venv/lib/python3.6/site-packages/asphalt/core/util.py", line 30, in resolve_reference
    obj = import_module(modulename)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/doezer/git_projects/OWAPI/owapi/app.py", line 21, in <module>
    from owapi.v3 import api_v3
  File "/home/doezer/git_projects/OWAPI/owapi/v3/__init__.py", line 46, in <module>
    @api_v3.route("/u/<battletag>/blob", reverse_hooks=True)
TypeError: route() got an unexpected keyword argument 'reverse_hooks'
```

Thanks for your help

**Comment by SunDwarf** [comment]
Have you ran `pip install -r requirements.txt` to update all the deps recently?

**Comment by Doezer** [comment]
Thank you, that did the trick. I'll remember it next time. First time for me using a git repo as as a production tool so I kinda forgot that updates were needed from time to time.
```
pip install -r requirements.txt
Collecting Kyoukai<=2.3.0,>=2.1.4 (from -r requirements.txt (line 1))
  Downloading Kyoukai-2.1.4-py3-none-any.whl
Requirement already satisfied: aioredis==0.3.0 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Collecting aiohttp<=2.1.0,>=2.0.7 (from -r requirements.txt (line 3))
  Downloading aiohttp-2.1.0-cp36-cp36m-manylinux1_x86_64.whl (661kB)
    100% |████████████████████████████████| 665kB 505kB/s
Collecting asphalt==3.0.0 (from -r requirements.txt (line 4))
  Downloading asphalt-3.0-py3-none-any.whl
Collecting asphalt-redis==2.0.0 (from -r requirements.txt (line 5))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/asphalt-redis/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)",)': /simple/asphalt-redis/
  Downloading asphalt_redis-2.0.0-py3-none-any.whl
Requirement already satisfied: asyncio-extras<=1.4.0,>=1.3.0 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Collecting lxml==3.7.3 (from -r requirements.txt (line 7))
  Using cached lxml-3.7.3-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: unidecode==0.04.19 in ./venv/lib/python3.6/site-packages (from -r requirements.txt (line 8))
Collecting h2>=3.0.0 (from Kyoukai<=2.3.0,>=2.1.4->-r requirements.txt (line 1))
  Downloading h2-3.0.1-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 81kB 2.4MB/s
Requirement already satisfied: werkzeug>=0.11.10 in ./venv/lib/python3.6/site-packages (from Kyoukai<=2.3.0,>=2.1.4->-r requirements.txt (line 1))
Requirement already satisfied: httptools>=0.0.9 in ./venv/lib/python3.6/site-packages (from Kyoukai<=2.3.0,>=2.1.4->-r requirements.txt (line 1))
Requirement already satisfied: hiredis in ./venv/lib/python3.6/site-packages (from aioredis==0.3.0->-r requirements.txt (line 2))
Collecting multidict>=2.1.4 (from aiohttp<=2.1.0,>=2.0.7->-r requirements.txt (line 3))
  Downloading multidict-2.1.6-cp36-cp36m-manylinux1_x86_64.whl (365kB)
    100% |████████████████████████████████| 368kB 899kB/s
Requirement already satisfied: chardet in ./venv/lib/python3.6/site-packages (from aiohttp<=2.1.0,>=2.0.7->-r requirements.txt (line 3))
Collecting yarl<0.11,>=0.10.0 (from aiohttp<=2.1.0,>=2.0.7->-r requirements.txt (line 3))
  Downloading yarl-0.10.3-cp36-cp36m-manylinux1_x86_64.whl (167kB)
    100% |████████████████████████████████| 174kB 1.7MB/s
Collecting async-timeout>=1.2.0 (from aiohttp<=2.1.0,>=2.0.7->-r requirements.txt (line 3))
  Using cached async_timeout-1.2.1-py3-none-any.whl
Requirement already satisfied: click>=6.6 in ./venv/lib/python3.6/site-packages (from asphalt==3.0.0->-r requirements.txt (line 4))
Requirement already satisfied: ruamel.yaml>=0.12 in ./venv/lib/python3.6/site-packages (from asphalt==3.0.0->-r requirements.txt (line 4))
Requirement already satisfied: typeguard~=2.0 in ./venv/lib/python3.6/site-packages (from asphalt==3.0.0->-r requirements.txt (line 4))
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages (from asphalt==3.0.0->-r requirements.txt (line 4))
Requirement already satisfied: async-generator~=1.4 in ./venv/lib/python3.6/site-packages (from asphalt==3.0.0->-r requirements.txt (line 4))
Requirement already satisfied: hpack<4,>=2.3 in ./venv/lib/python3.6/site-packages (from h2>=3.0.0->Kyoukai<=2.3.0,>=2.1.4->-r requirements.txt (line 1))
Requirement already satisfied: hyperframe<6,>=5.0 in ./venv/lib/python3.6/site-packages (from h2>=3.0.0->Kyoukai<=2.3.0,>=2.1.4->-r requirements.txt (line 1))
Installing collected packages: h2, asphalt, Kyoukai, multidict, yarl, async-timeout, aiohttp, asphalt-redis, lxml
  Found existing installation: h2 2.6.1
    Uninstalling h2-2.6.1:
      Successfully uninstalled h2-2.6.1
  Found existing installation: asphalt 2.1.1
    Uninstalling asphalt-2.1.1:
      Successfully uninstalled asphalt-2.1.1
  Found existing installation: Kyoukai 2.0.4.1
    Uninstalling Kyoukai-2.0.4.1:
      Successfully uninstalled Kyoukai-2.0.4.1
  Found existing installation: multidict 1.2.2
    Uninstalling multidict-1.2.2:
      Successfully uninstalled multidict-1.2.2
  Found existing installation: aiohttp 0.22.5
    Uninstalling aiohttp-0.22.5:
      Successfully uninstalled aiohttp-0.22.5
  Found existing installation: asphalt-redis 1.0.0
    Uninstalling asphalt-redis-1.0.0:
      Successfully uninstalled asphalt-redis-1.0.0
  Found existing installation: lxml 3.6.1
    Uninstalling lxml-3.6.1:
      Successfully uninstalled lxml-3.6.1
Successfully installed Kyoukai-2.1.4 aiohttp-2.1.0 asphalt-3.0 asphalt-redis-2.0.0 async-timeout-1.2.1 h2-3.0.1 lxml-3.7.3 multidict-2.1.6 yarl-0.10.3
```
