### ISSUE TITLE
Problem with run server (cannot import module)

### ISSUE THREAD

**Issue by OverwatchJohnson** [SunDwarf/OWAPI#182]
## Issue

Instalation

## Links that cause the issue

(Surround the links with backticks. Use triple backticks for multiple lines.)

`https://owapi.net/api/v3/u/Dad-12262/blob`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [x] Google/Search previous issues to make sure it hasn't been answered before.

* [x] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

Hello, i have problem with run server. My error:
(venv) johnson@johnson-VirtualBox:~$ PYTHONPATH=. asphalt run config.yml
INFO:asphalt.core.runner:Running in development mode
Traceback (most recent call last):
  File "/home/johnson/venv/lib/python3.5/site-packages/asphalt/core/util.py", line 30, in resolve_reference
    obj = import_module(modulename)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'owapi'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/johnson/venv/bin/asphalt", line 11, in <module>
    sys.exit(main())
  File "/home/johnson/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/johnson/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/johnson/venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/johnson/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/johnson/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/johnson/venv/lib/python3.5/site-packages/asphalt/core/command.py", line 34, in run
    run_application(**config)
  File "/home/johnson/venv/lib/python3.5/site-packages/asphalt/core/runner.py", line 90, in run_application
    component = component_types.create_object(**component)
  File "/home/johnson/venv/lib/python3.5/site-packages/asphalt/core/util.py", line 146, in create_object
    plugin_class = self.resolve(type)
  File "/home/johnson/venv/lib/python3.5/site-packages/asphalt/core/util.py", line 120, in resolve
    return resolve_reference(obj)
  File "/home/johnson/venv/lib/python3.5/site-packages/asphalt/core/util.py", line 33, in resolve_reference
    'error resolving reference {}: could not import module'.format(ref)) from e
LookupError: error resolving reference owapi.app:APIComponent: could not import module

Requirements.txt installed,
Repository cloned,
Python version 3.5

I dont know what is wrong and Google doesnt help.

**Comment by SunDwarf** [comment]
`export PYTHONPATH=.` before running

**Comment by OverwatchJohnson** [comment]
unfortunately still doesnt work (same error -> cant import module)
