### ISSUE TITLE
500 error while fetching user stats

### ISSUE THREAD

**Issue by Double0negative** [SunDwarf/OWAPI#187]
## Issue
Error when trying to fetch users stats.

```{"msg": "please report this!", "error": 500, "exc": "TypeError(\"__init__() got an unexpected keyword argument 'proxy_from_env'\",)"}```

## Links that cause the issue

(Surround the links with backticks. Use triple backticks for multiple lines.)

Any

Error:

```
2017-07-10 21:05:57,808 - [INFO] Kyoukai -> Hit HTTPException (500 Internal Server Error: The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.) inside function, delegating.
2017-07-10 21:05:57,808 - [ERROR] OWAPI -> Unhandled exception - Blizzard format probably changed!
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/programming/web/OWAPI/owapi/blizz_interface.py", line 85, in get_user_page
    page_body = await get_page_body(ctx, built_url, cache_time=cache_time, cache_404=cache_404)
  File "/programming/web/OWAPI/owapi/blizz_interface.py", line 49, in get_page_body
    cache_404=cache_404)
  File "/programming/web/OWAPI/owapi/util.py", line 55, in with_cache
    result = await func(ctx, *args)
  File "/programming/web/OWAPI/owapi/blizz_interface.py", line 41, in _real_get_body
    async with ctx.session.get(url) as req:
  File "/programming/web/OWAPI/venv/lib/python3.5/site-packages/aiohttp/client.py", line 626, in __aenter__
    self._resp = yield from self._coro
  File "/programming/web/OWAPI/venv/lib/python3.5/site-packages/aiohttp/client.py", line 220, in _request
    proxy=proxy, proxy_auth=proxy_auth, timer=timer)
  File "/programming/web/OWAPI/owapi/app.py", line 44, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'proxy_from_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/programming/web/OWAPI/venv/lib/python3.5/site-packages/kyoukai/app.py", line 273, in process_request
    result = await matched.invoke(ctx, params)
  File "/programming/web/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 244, in invoke
    return await self.invoke_function(ctx, pre_hooks, post_hooks, params)
  File "/programming/web/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 115, in invoke_function
    raise e
  File "/programming/web/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 110, in invoke_function
    result = await result
  File "/programming/web/OWAPI/owapi/v3/v3_util.py", line 63, in _rl_inner2
    return await func(ctx, *args, **kwargs)
  File "/programming/web/OWAPI/owapi/v3/__init__.py", line 51, in get_blob
    platform=ctx.request.args.get("platform", "pc"))
  File "/programming/web/OWAPI/owapi/blizz_interface.py", line 147, in fetch_all_user_pages
    raise e
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.
2017-07-10 21:05:57,808 - [INFO] Kyoukai -> GET /api/v3/u/Jacklz-1334/blob - 500

```

**Comment by SunDwarf** [comment]
I can't reproduce this. Are all your requirements up to date?

**Comment by Double0negative** [comment]
Oops, it appears that was the problem, It is working now after a requirements updated.
