### ISSUE TITLE
Cannot retrieve player info

### ISSUE THREAD

**Issue by Doezer** [SunDwarf/OWAPI#191]
## Issue

When I try to retrieve a player info, I get this response : 
{"error": 500, "msg": "please report this!", "exc": "KeyError('eliminations_avg',)"}

I have done a git pull but there's no updates.

Full stack trace : 
```
2017-07-28 10:23:55,402 - [INFO] OWAPI -> GET => https://playoverwatch.com/en-us/career/pc/us/LePetitChat-21940 => 200
2017-07-28 10:23:55,425 - [INFO] OWAPI -> Storing _real_get_body('https://playoverwatch.com/en-us/career/pc/us/LePetitChat-21940',) with expiration 300
2017-07-28 10:23:55,767 - [ERROR] Kyoukai -> Unhandled exception in route function
Traceback (most recent call last):
  File "/OWAPI/venv/lib/python3.6/site-packages/kyoukai/app.py", line 273, in process_request
    result = await matched.invoke(ctx, params)
  File "/OWAPI/venv/lib/python3.6/site-packages/kyoukai/route.py", line 244, in invoke
    return await self.invoke_function(ctx, pre_hooks, post_hooks, params)
  File "/OWAPI/venv/lib/python3.6/site-packages/kyoukai/route.py", line 110, in invoke_function
    result = await result
  File "/OWAPI/owapi/v3/v3_util.py", line 123, in _rl_inner2
    return await func(ctx, *args, **kwargs)
  File "/OWAPI/owapi/v3/__init__.py", line 98, in get_stats
    d["stats"]["quickplay"] = parsing.bl_parse_stats(result)
  File "/OWAPI/owapi/v3/parsing.py", line 239, in bl_parse_stats
    average_keys = ("eliminations", "healing_done", "final_blows", "objective_kills")
KeyError: 'eliminations_avg'
2017-07-28 10:23:55,769 - [ERROR] OWAPI -> Unhandled exception - Blizzard format probably changed!
Traceback (most recent call last):
  File "/OWAPI/venv/lib/python3.6/site-packages/kyoukai/app.py", line 273, in process_request
    result = await matched.invoke(ctx, params)
  File "/OWAPI/venv/lib/python3.6/site-packages/kyoukai/route.py", line 244, in invoke
    return await self.invoke_function(ctx, pre_hooks, post_hooks, params)
  File "/OWAPI/venv/lib/python3.6/site-packages/kyoukai/route.py", line 110, in invoke_function
    result = await result
  File "/OWAPI/owapi/v3/v3_util.py", line 123, in _rl_inner2
    return await func(ctx, *args, **kwargs)
  File "/OWAPI/owapi/v3/__init__.py", line 98, in get_stats
    d["stats"]["quickplay"] = parsing.bl_parse_stats(result)
  File "/OWAPI/owapi/v3/parsing.py", line 239, in bl_parse_stats
    average_keys = ("eliminations", "healing_done", "final_blows", "objective_kills")
KeyError: 'eliminations_avg'
2017-07-28 10:23:55,771 - [INFO] Kyoukai -> GET /api/v3/u/LePetitChat-21940/stats - 500
```

## Links that cause the issue
The issue seems not to be present on owapi.net

Thanks!

**Comment by SunDwarf** [comment]
This isn't possible; the place where a keyerror could happen is wrapped in a try/except for it.

**Comment by Doezer** [comment]
I understand but it is happening nonetheless (for every player). I can provide more info if needed

**Comment by naddison** [comment]
I am receiving the same error.

2017-07-28 23:05:19,392 - [ERROR] Kyoukai -> Unhandled exception in route function
Traceback (most recent call last):
  File "/owapi/OWAPI/venv/lib/python3.5/site-packages/kyoukai/app.py", line 293, in process_request
    result = await matched.invoke(ctx, params=params)
  File "/owapi/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 268, in invoke
    return await self.invoke_function(ctx, pre_hooks, post_hooks, params)
  File "/owapi/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 129, in invoke_function
    result = await result
  File "/owapi/OWAPI/owapi/v3/v3_util.py", line 63, in _rl_inner2
    return await func(ctx, *args, **kwargs)
  File "/owapi/OWAPI/owapi/v3/__init__.py", line 63, in get_blob
    d["stats"]["quickplay"] = parsing.bl_parse_stats(result)
  File "/owapi/OWAPI/owapi/v3/parsing.py", line 239, in bl_parse_stats
    avg_elim = built_dict["average_stats"]["eliminations_avg"]
KeyError: 'eliminations_avg'
2017-07-28 23:05:19,393 - [ERROR] OWAPI -> Unhandled exception - Blizzard format probably changed!
Traceback (most recent call last):
  File "/owapi/OWAPI/venv/lib/python3.5/site-packages/kyoukai/app.py", line 293, in process_request
    result = await matched.invoke(ctx, params=params)
  File "/owapi/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 268, in invoke
    return await self.invoke_function(ctx, pre_hooks, post_hooks, params)
  File "/owapi/OWAPI/venv/lib/python3.5/site-packages/kyoukai/route.py", line 129, in invoke_function
    result = await result
  File "/owapi/OWAPI/owapi/v3/v3_util.py", line 63, in _rl_inner2
    return await func(ctx, *args, **kwargs)
  File "/owapi/OWAPI/owapi/v3/__init__.py", line 63, in get_blob
    d["stats"]["quickplay"] = parsing.bl_parse_stats(result)
  File "/owapi/OWAPI/owapi/v3/parsing.py", line 239, in bl_parse_stats
    avg_elim = built_dict["average_stats"]["eliminations_avg"]
KeyError: 'eliminations_avg'

**Comment by SunDwarf** [comment]
@Doezer Are you sure you're *running* the latest version (i.e. rebooting after pulled)?

@naddison Update your copy.

**Comment by Doezer** [comment]
Rebooting the supervisor service did the trick. I'm guessing I forgot to reboot after a previous update.

**Comment by naddison** [comment]
When was this fixed and what was the fix?

**Comment by SunDwarf** [comment]
11th July in a9d38226230807a11b0f124bbb44959e373b7ea6.
