### ISSUE TITLE
asyncio.TimeoutError while recieving profiles

### ISSUE THREAD

**Issue by KingJP** [SunDwarf/OWAPI#205]
## Issue

Hi there!

While recieving 50 Overwatch Profiles asynchronously at the same time I get the error shown below. At the moment I am using the configuration shown below on Debian 9. Has anyone a idea why I get this error? When I open the link in the browser I don't get the timeout error.

## Links that cause the issue

(Surround the links with backticks. Use triple backticks for multiple lines.)

`http://localhost/api/v3/u/Griessly-2742/blob`

## Error Message

```
Nov  1 19:37:03 root3 owapi[27467]: 2017-11-01 19:37:03,603 - [ERROR] OWAPI -> Failed to fetch user page!
Nov  1 19:37:03 root3 owapi[27467]: Traceback (most recent call last):
Nov  1 19:37:03 root3 owapi[27467]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
Nov  1 19:37:03 root3 owapi[27467]:     result = coro.throw(exc)
Nov  1 19:37:03 root3 owapi[27467]:   File "/opt/OWAPI/owapi/blizz_interface.py", line 85, in get_user_page
Nov  1 19:37:03 root3 owapi[27467]:     page_body = await get_page_body(ctx, built_url, cache_time=cache_time, cache_404=cache_404)
Nov  1 19:37:03 root3 owapi[27467]:   File "/opt/OWAPI/owapi/blizz_interface.py", line 49, in get_page_body
Nov  1 19:37:03 root3 owapi[27467]:     cache_404=cache_404)
Nov  1 19:37:03 root3 owapi[27467]:   File "/opt/OWAPI/owapi/util.py", line 35, in with_cache
Nov  1 19:37:03 root3 owapi[27467]:     result = await func(ctx, *args)
Nov  1 19:37:03 root3 owapi[27467]:   File "/opt/OWAPI/owapi/blizz_interface.py", line 41, in _real_get_body
Nov  1 19:37:03 root3 owapi[27467]:     async with ctx.session.get(url) as req:
Nov  1 19:37:03 root3 owapi[27467]:   File "/opt/OWAPI/venv/lib/python3.5/site-packages/aiohttp/client.py", line 603, in __aenter__
Nov  1 19:37:03 root3 owapi[27467]:     self._resp = yield from self._coro
Nov  1 19:37:03 root3 owapi[27467]:   File "/opt/OWAPI/venv/lib/python3.5/site-packages/aiohttp/client.py", line 241, in _request
Nov  1 19:37:03 root3 owapi[27467]:     yield from resp.start(conn, read_until_eof)
Nov  1 19:37:03 root3 owapi[27467]:   File "/opt/OWAPI/venv/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 572, in start
Nov  1 19:37:03 root3 owapi[27467]:     self._continue = None
Nov  1 19:37:03 root3 owapi[27467]:   File "/opt/OWAPI/venv/lib/python3.5/site-packages/aiohttp/helpers.py", line 743, in __exit__
Nov  1 19:37:03 root3 owapi[27467]:     raise asyncio.TimeoutError from None
Nov  1 19:37:03 root3 owapi[27467]: concurrent.futures._base.TimeoutError
```

## Configuration

```
---
component:
  # Do not change this line. Everything will break.
  type: owapi.app:APIComponent

  # Is caching via redis enabled?
  # This will speed up the API massively for subsequent requests, but data will be stale for 300 seconds.
  # Set to False to disable.
  use_redis: False

  # Enable profiling?
  # This is only recommended for developers.
  do_profiling: False

  # Disable ratelimiting?
  # This prevents spam for public instances. Private instances should set this to True.
  disable_ratelimits: True

  # The time to cache results for.
  # By default, this is 300.
  # If `use_redis` is False, this statement has no effect.
  # If this remains commented, the cache time used will be the default for functions.
  #cache_time: 300

  # Components listing. Do not edit.
  components:
    # The webapp component.
    kyoukai:
      # Do not change this line. Everything will break.
      app: owapi.app:app
      # Launch the app in debug mode? Recommended False for production servers.
      debug: False
      # The IP for Kyoukai to bind to.
      # ip: 127.0.0.1
      ip: 127.0.0.1
      # The port for Kyoukai to bind to.
      port: 4444
    # The redis component.
    # This is ignored if `use_redis` is set to False.
    redis:
      connections:
        redis:
          # The address of your Redis server.
          address: 127.0.0.1
          # The port of your Redis server.
          port: 6379
          # The database to connect to on Redis.
          db: 1
          # The password for your Redis server.
          # Do not uncomment if you do not have a password.
          # password: hunter2

          # Enable SSL for this redis connection?
          # This must be enabled on the server side too.
          ssl: False
```

**Comment by KingJP** [comment]
13 Contributors and no one has any idea?

**Comment by Js41637** [comment]
Beats me, does it happen when you don't request so many at once?

**Comment by azah** [comment]
If you read the error message it says async.io times out.

`raise asyncio.TimeoutError from None`

The error stems from `page_body = await get_page_body(ctx, built_url, cache_time=cache_time, cache_404=cache_404)` in `blizz_interface.py`.

Looks like the function needs to `catch` TimeOutError`.
@SunDwarf

https://stackoverflow.com/questions/30836703/asyncio-catch-timeouterror-in-task

https://www.programcreek.com/python/example/81580/asyncio.TimeoutError

**Comment by KingJP** [comment]
Thank You for your investigations!

I have found the cause of the error in the API calling code. The Node.JS Script called the api about 50 times at the same time. Maybe Blizzard blocked some of my requests for security reasons. I changed my code to execute one request after another. This works for me.
