### ISSUE TITLE
UTF-8 Decode Issue

### ISSUE THREAD

**Issue by azah** [SunDwarf/OWAPI#48]
Running
```
http://localhost:4444/api/v2/u/Dad-12262/stats/general
```

gives me this error:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/kyokai/app.py", line 326, in delegate_request
    response = await route.invoke(self, ctx)
  File "/usr/local/lib/python3.5/site-packages/kyokai/route.py", line 92, in invoke
    result = await self._wrapped_coro(ctx, *matches)
  File ".../OWAPI/owapi/util.py", line 53, in res
    result = await func(ctx, *args)
  File ".../OWAPI/owapi/routes.py", line 144, in bl_get_stats
    platform=ctx.request.values.get("platform", "pc"))
  File ".../OWAPI/owapi/blizz_interface.py", line 88, in region_helper
    page = await get_user_page(ctx, battletag, platform, reg, extra)
  File ".../OWAPI/owapi/blizz_interface.py", line 59, in get_user_page
    page_body = await get_page_body(ctx, built_url, cache_time=cache_time)
  File ".../Python/OWAPI/owapi/blizz_interface.py", line 36, in get_page_body
    result = await util.with_cache(ctx, _real_get_body, url, expires=cache_time)
  File ".../OWAPI/owapi/util.py", line 36, in with_cache
    result = await func(ctx, *args)
  File ".../OWAPI/owapi/blizz_interface.py", line 34, in _real_get_body
    return (await req.read()).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

`0x8b` being `‹` according to [here](http://www.idautomation.com/product-support/ascii-chart-char-set.html).

**Comment by SunDwarf** [comment]
aiohttp issue.
	
Downgrade to 0.21.6.

**Comment by azah** [comment]
Thank you! 👍
